# Generated by Django 4.2.2 on 2023-07-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('mobile', models.IntegerField(blank=True, null=True, verbose_name='Mobile No.')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Password')),
                ('role', models.CharField(choices=[('1', ''), ('2', 'Customer'), ('3', 'Admin')], default=0, max_length=2, verbose_name='Role')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('sla_unlock', models.IntegerField(blank=True, null=True, verbose_name='SLA Unlock')),
                ('sla_lock', models.IntegerField(blank=True, null=True, verbose_name='SLA Lock')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_purchase', to='backend.customer', verbose_name='Customer')),
            ],
        ),
    ]
